ui: tape
browsers:
  - name: chrome
    version: '34..latest'
  - name: firefox
    version: '29..latest'
  - name: safari
    version: '7..latest'
  - name: iphone
    version: '7.0..latest'
  - name: android
    version: '4.0..latest'
scripts:
  - './dist/account-api.js'
